### ISSUE TITLE
[Feature]: Update content Pakt

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/website#20]
### What do you like to be improved?

Only update content

**Comment by phollome** [comment]
Please contact Anna and Lillit for final texts

**Comment by nac62116** [comment]
Final texts should be available during the next week/s

**Comment by sstenz** [comment]
@nac62116 Is this really the final text? Because we have in both paragraphs the part: "Mädchen und junge Frauen für MINT-Ausbildungen, -Studiengänge und -Berufe zu begeistern"
