### ISSUE TITLE
[Feature]: Implement Matomo

### ISSUE THREAD

**Issue by phollome** [mint-vernetzt/website#21]
### What do you like to be improved?

What we want to know:

- Anzahl Aufrufe Website (allgemein sowie über LinkedIn, Newsletter, Insta, Twitter)
- Anzahl Aufrufe Blogbeiträge
- Anzahl Aufrufe Dossier
- Anzahl Aufrufe News
- Anzahl Aufrufe Veranstaltungen
- Anzahl Aufrufe Ausschreibungen
- Durchschnittliche Aufenthaltsdauert auf der Website
- Durchschnittliche Aufenthaltsdauert auf den Blogbeiträgen (oder im newsbereich)
- Durchschnittliche Aufenthaltsdauert auf dem Dossier

estimate 4h

**Comment by nac62116** [comment]
Einsatz Matomo ohne Einwilligung (Auswertung von Logfiles):

Es besteht auch die Möglichkeit, Matomo ohne Cookies und ohne Device Fingerprinting zu verwenden. Es werden dann nur die Logdateien der Webseite in regelmäßigen Abständen in Matomo eingelesen. Diese Dateien speichern jede Anfrage an den Webserver einer Webseite (jede Seite/Bild/Datei/CSS- oder Javascript-Datei wird dort als Eintrag abgelegt). Dabei werden auch Informationen über den Nutzer protokolliert in sogenannten Logfile-Imports. Hieraus lassen sich u.a. Auskünfte zur Besucheranzahl, Browser, Geräte, Betriebssystem erzeugen. Diese Angaben sind aber sehr ungenau. Eine Einwilligung ist bei dieser Variante nach einschlägiger Meinung des LfDI Baden-Württemberg nicht erforderlich. Allerdings bietet diese Analyse nur einen Bruchteil der Auswertungen, die Matomo normalerweise bieten kann. Umfangreiches Tracking wäre hier wohl aus technischer Sicht nicht möglich.
 
Einbindung von Matomo ohne Einwilligung:
 
- Um ein Cookie-Tracking für Matomo abzustellen, ist in den „erweiterten Einstellungen“ die Option „Alle Tracking Cookies deaktivieren“ auszuwählen. Alternativ kann zum Deaktivieren der Cookies für Matomo auch der Java-Script-Code modifiziert werden. Eine entsprechende Anleitung dazu ist [hier](https://matomo.org/faq/general/faq_157/) zu finden. 
Die IP-Adressen sind zu anonymisieren. Es sollten hier mindestens zwei Bytes anonymisiert werden (ein Byte ist nicht ausreichend). Dies kann in den Administrationseinstellungen unter „Privatsphäre“ –„Daten anonymisieren“ eingestellt werden.
- Die „Do-not-track“-Unterstützung sollte durch den Webseitenbetreiber aktiviert werden. Die Nutzer können in ihrem Browser selbst einstellen, ob sie Webseiten dazu auffordern wollen, das Tracking zu unterlassen. Wenn die Unterstützungsfunktion aktiviert wird, kann Matomo die Nutzer nicht tracken. Diese Einstellung erfolgt durch den Webseitenbetreiber unter „Privatsphäre“ – „Benutzer-opt-out“.
- In der Datenschutzerklärung sollte die Verwendung von Matomo aufgeführt werden.
- Empfehlenswert wäre darüber hinaus, in der Datenschutzerklärung ein Opt-Out-iFrame einzubinden. Dies ermöglicht dem Nutzer per Klick die Option, sich der Nutzerzählung zu entziehen. Dieses Opt-Out-iFrame lässt sich durch den Webseitenbetreiber in den Administrationseinstellungen von Matomo unter „Privatsphäre“ – „Benutzer-opt-out“ erstellen.
Zudem sollte überprüft werden, ob die Daten in regelmäßigen Abständen von Matomo gelöscht werden unter Berücksichtigung des Grundsatzes der Datenminimierung und Speicherbegrenzung gemäß DS-GVO. Dies kann unter den Privatsphäre-Einstellungen von Matomo vorgenommen werden („Daten anonymisieren“ – „Lösche regelmäßig alte Daten aus der Datenbank“).
- Bei Verwendung von Logfiles sollten diese auf den Servern des Webseitenbetreibers verbleiben und nicht an Dritte weitergegeben werden.

**Comment by nac62116** [comment]
Recommended plugins by manu:

- SecurityInfo by Matomo -> More security informations
- CustomOptOut -> CSS for opt-out-iFrame
- BotTracker -> Cleaning data
- DevicePixelRatio -> Provide information about Retina usage

**Comment by nac62116** [comment]
TODO:

- Implement crontab Logfile-Rotation for matomo
