### ISSUE TITLE
[Feature]: Apply new landing page design

### ISSUE THREAD

**Issue by nac62116** [mint-vernetzt/website#72]
- [x] Cut off "Aktiv werden" section 
- [x] Link to Plattform
- [x] "Our Projects" section
- [x] Change year in footer automatically

Styles see [Figma](https://www.figma.com/file/EcsrhGDlDkVEYRAI1qmcD6/MINTvernetzt?node-id=2437%3A26765)
Files see [Files](https://matrixgruppe.sharepoint.com/:f:/r/sites/TeamEXTERNMINT-E-Plattform/Shared%20Documents/General/Websitestruktur/Restrukturierung_2022?csf=1&web=1&e=EoySnR)

**Comment by sstenz** [comment]
Change year in footer manually
